# Generated by Django 4.2.3 on 2023-07-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_trendingproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrendingProduct',
            new_name='Weekly_Deal',
        ),
    ]
