# Generated by Django 4.2.3 on 2023-07-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_trendingproduct_weekly_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly_deal',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
